---
title: "p8105_hw2_sl4657"
output: github_document
editor_options: 
  chunk_output_type: console
---

# Problem 1
## Use Mr.Trash.Wheel sheet
```{r}
library(tidyverse)
library(readxl)
library(dplyr)
mtw_data = 
  read_excel(
    "data files/HealthyHarborWaterWheelTotals2018-7-28.xlsx", sheet=1) %>% 
  janitor::clean_names() %>% 
  filter(!is.na(dumpster))%>% 
  select(-15) %>% 
  mutate(sports_balls = round(sports_balls, digits = 0)) %>% 
  mutate(sports_balls = as.integer(sports_balls))
```

```{r}
p8_data = 
  readxl::read_excel(
    "./data files/HealthyHarborWaterWheelTotals2018-7-28.xlsx", sheet=3,range = "A2:B14") %>% 
  janitor::clean_names() %>% 
  drop_na() %>% 
  mutate(year= "2018")

p7_data = 
  readxl::read_excel(
    "./data files/HealthyHarborWaterWheelTotals2018-7-28.xlsx", sheet=4,range = "A2:B14") %>% 
  janitor::clean_names() %>% 
  mutate(year= "2017")

p78_data=
  bind_rows(p7_data, p8_data) %>% 
  mutate(month = month.abb[month]) %>% 
  select(year, everything())
```
The number of observations in 2018 precipitation dataset is `r nrow(p8_data)`, in 2017 precipitation dataset is `r nrow(p7_data)`, key variables are `r colnames(p78_data[1:2])`. The total precipitation in 2018 is `r sum(pull(p8_data, total))`, the median number of sports balls in a dumpster in 2017 is `r median(pull(mtw_data,sports_balls), 167:221)`.

# Problem 2
##  Use the FiveThirtyEight data
```{r}
pols_data = 
  read_csv(file = "./data files/pols-month.csv") %>% 
  separate(col = mon, into = c("year", "month", "day"), "-") %>%
  mutate(month= recode(month, `01`= "Jan", `02`= "Feb", `03`= "Mar", `04`= "Apr", `05`= "May", `06`= "Jun", `07`= "Jul", `08`= "Aug", `09`= "Sep", `10`= "Oct", `11`= "Nov", `12`= "Dec")) %>% 
  select(-prez_gop, -prez_dem) %>% 
  pivot_longer(
    c(ends_with("gop"), ends_with("dem")),
    names_to = "party",
    values_to = "president"
  ) %>% 
  select(-day)
```





